#!/bin/sh

set -eu

for file in engine-histograms library-histograms
do
  echo "from $file\n\n"

  java -cp fix-gateway-system-tests-*-benchmarks.jar uk.co.real_logic.fix_gateway.timing.HistogramLogReader $file -s
done

